import { jsx as _jsx } from "react/jsx-runtime";
import React from "react";
import ReactDOM from "react-dom/client";
import { RouterProvider } from "react-router-dom";
import { AppProvider } from "./state/AppContext";
import { router } from "./routes";
import "@fontsource-variable/outfit";
import "@fontsource-variable/space-grotesk";
import "./theme.css";
import "./styles.css";
ReactDOM.createRoot(document.getElementById("root")).render(_jsx(React.StrictMode, { children: _jsx(AppProvider, { children: _jsx(RouterProvider, { router: router }) }) }));
